name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # Docker Hub credentials from repository secrets
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Step 3: Build and Push UserService
      - name: Build and Push UserService
        run: |
          docker build -t $DOCKER_USERNAME/userservice -f UserService/Dockerfile .
          docker push $DOCKER_USERNAME/userservice

      # Step 4: Build and Push AccountService
      - name: Build and Push AccountService
        run: |
          docker build -t $DOCKER_USERNAME/accountservice -f AccountService/Dockerfile .
          docker push $DOCKER_USERNAME/accountservice

      # Step 5: Build and Push OrderService
      - name: Build and Push OrderService
        run: |
          docker build -t $DOCKER_USERNAME/orderservice -f OrderService/Dockerfile .
          docker push $DOCKER_USERNAME/orderservice
